Header-hero
romaskirman/Project-Dudeshape pull request #1
Opened 2022-01-29 19:25 UTC by romaskirman

Добавил хедер, хиро секцию и секцию с логотипами

2022-01-29 21:24 UTC, aleksey-drozdov requested changes
нужно поправить названия файлов

2022-01-29 21:24 UTC, aleksey-drozdov commented on index.html
> +                <div>
заменить на тег nav

2022-01-29 21:24 UTC, aleksey-drozdov commented on index.html
> +                            <img src="assets/images/Arrow%20-%20Right%202right-stroke.png" alt="right stoke">
заменить названия картинок, что бы в них не было пробелов и русских букв.

2022-01-29 21:24 UTC, aleksey-drozdov commented on index.html
> +                            <img src="assets/images/Arrow%20-%20Right%203left-stroke.png" alt="left stroke">
поправить название файл

2022-01-29 21:24 UTC, aleksey-drozdov commented on assets/styles/style.css
> +    max-width: 1440px;
задать для секции выравнивание по центру страницы, сейчас она прижата к левому краю. 
аналогично для других секций

2022-01-29 21:24 UTC, aleksey-drozdov commented on assets/styles/style.css
> +    padding: 40px 100px;
на макете ширина контента хедера 1240px.  если ограничить ему максимальную ширину этим размером, то не нужны будут горизонтальные паддинги

2022-01-29 21:24 UTC, aleksey-drozdov commented on assets/styles/style.css
> +    padding-left: 100px;
аналогично, как и для хедера

2022-01-30 15:59 UTC, romaskirman commented on assets/styles/style.css
> +    max-width: 1440px;
я выравнивание задам после того как все свои ветки можно будет залить в dev, затем в dev пропишу один раз центрирование для всего

2022-01-30 16:03 UTC, romaskirman commented on assets/styles/style.css
> +    padding-left: 100px;
у хиро секции ширина не 1240 а 1440 у меня, там картинка если присмотреться и выделить ее, идёт до самого правого края

2022-01-31 21:25 UTC, merged